#!/bin/bash

# (c) 2008 Jasper Spaans <j@jasper.es>

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

worst=0
msg=""
if [ -e /dev/md?* ] ; then
  echo "OK" ;
  for dev in /dev/md?* ; do
    sudo /sbin/mdadm --misc -t $dev
    status=$?
    if [ $status == 0 ]; then
      msg="MD: ${msg} ${dev}: ok"
    elif [ $status == 1 ] ; then
      if [ worst != 2 ] ; then
        worst=1
      fi
      msg="MD: ${msg} ${dev}: degraded"
    elif [ $status == 2 ] ; then
      worst=2
      msg="MD: ${msg} ${dev}: unusable"
    fi
  done
else
  msg="MD: No md devices"
fi

echo $msg
exit $worst
